Add server manager hint explanation
CatenaTools/documentation pull request #11
Opened 2024-05-20 20:32 UTC by doctaweeks

2024-05-23 18:24 UTC, jlyon1 requested changes
Minor recommendation

2024-05-23 18:24 UTC, jlyon1 commented on Writerside/topics/Server-Manager.md
> +When a game server is idle (or backfilling or running matches in parallel) and has room for a new match it can
For this section and the other requests, lets pull in the openapi docs now that they are being generated. They are located in this directory: https://github.com/CatenaTools/documentation/tree/main/Writerside/apispec/openapi

2024-05-23 18:24 UTC, jlyon1 commented on Writerside/topics/Server-Manager.md
> +When a game server is idle (or backfilling or running matches in parallel) and has room for a new match it can
They can be under a collapsible section so they aren't the main draw.

2024-05-24 13:19 UTC, hunterfortuin commented
Not necessarily directly related to this review, but something that is related to a topic brought up in #9 and was added [here](https://github.com/CatenaTools/documentation/pull/9/commits/05e2f7565df397e794af6b0f3c962f51b683b9a2#diff-08e2dc4d4101c1b6c8eac3f22f43d0f3d579e6acc686be9c2839b986a49c3d31R67).

I think it would be helpful to show some diagrams showing how each of these components fit together (game client, matchmaker, match broker, server manager, etc) so readers can more easily visualize the system.

2024-05-31 18:12 UTC, doctaweeks commented
> Not necessarily directly related to this review, but something that is related to a topic brought up in #9 and was added [here](https://github.com/CatenaTools/documentation/pull/9/commits/05e2f7565df397e794af6b0f3c962f51b683b9a2#diff-08e2dc4d4101c1b6c8eac3f22f43d0f3d579e6acc686be9c2839b986a49c3d31R67).
> 
> I think it would be helpful to show some diagrams showing how each of these components fit together (game client, matchmaker, match broker, server manager, etc) so readers can more easily visualize the system.

Good call - started here with the server manager: https://github.com/CatenaTools/documentation/pull/19

I will do another for the integrated match broker.

2024-06-18 20:39 UTC, jlyon1 commented on Writerside/topics/Server-Manager.md
> +When a game server is idle (or backfilling or running matches in parallel) and has room for a new match it can
We can address this in a later standardization effort

2024-06-18 20:39 UTC, jlyon1 approved these changes

2024-06-20 15:48 UTC, merged